# Generated by Django 4.0.4 on 2022-05-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_batchtiming_options'),
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='batch',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='batches.batch'),
            preserve_default=False,
        ),
    ]
