# Generated by Django 4.0.4 on 2022-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_usertest_completed_on_usertest_started_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='marks_gained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_taken',
            field=models.DurationField(),
        ),
    ]
