# Generated by Django 4.0.4 on 2022-05-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_userquestion_time_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='time_taken',
        ),
    ]
