# Generated by Django 4.0.4 on 2022-05-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_remove_usertest_time_taken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicPerformance',
        ),
    ]
