# Generated by Django 4.0.4 on 2022-05-17 10:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_delete_topicperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, unique=True),
        ),
    ]
