# Generated by Django 5.1.1 on 2024-10-02 16:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_delete_topicperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
