# Generated by Django 4.0.4 on 2022-05-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtiming',
            options={'ordering': ['opening_time']},
        ),
    ]
