# Generated by Django 4.0.4 on 2022-04-22 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'The phone number you entered has already been registered!'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Phone Number is invalid!', regex='^\\+?1?\\d{8,15}$')])),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], max_length=15)),
                ('salutation', models.CharField(choices=[('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Prof', 'Prof'), ('Rev', 'Rev')], default='Mr', max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
