# Generated by Django 4.0.4 on 2022-04-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mainexam',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
